spring:
  application:
    name: Backend_HAS-200
  profiles:
    active: dev
  main:
    banner-mode: off
server:
  port: 8080

app:
  jwt:
    secret: ${JWT_SECRET}
    issuer: has200-learning
    access-ttl: 15m
    refresh-ttl: 7d
